version: "3.3"

services:

  traefik:
    image: "traefik:v2.0.0-rc3"
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "9090:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  auth-api:
    build: ./auth-api
    container_name: "auth-api-service"
    ports:
      - "12345:8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth-api.rule=PathPrefix(`/auth-api`)"
      - "traefik.http.routers.auth-api.entrypoints=web"
      # - "traefik.http.middlewares.test-stripprefix.stripprefix.prefixes=/auth-api"
      - "traefik.http.services.auth-api-service.loadbalancer.server.port=8080"
    depends_on:
      - auth-api-db
      
  packages-api:
    build: ./packages-api
    container_name: "packages-api-service"
    ports:
      - "12346:8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.packages-api.rule=PathPrefix(`/packages-api`)"
      - "traefik.http.routers.packages-api.entrypoints=web"
      - "traefik.http.services.packages-api-service.loadbalancer.server.port=8080"
    depends_on:
      - packages-api-db
  auth-api-db:
    container_name: auth-api-db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: f5gd83diehd94erf94
      
  packages-api-db:
    container_name: packages-api-db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: f5gd83diehd94erf94
